import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Home,ShoppingCart,ReceiptText,User,Search,Bell,MapPin,Plus,Minus,Heart,ArrowLeft,CheckCircle2,Circle,Clock,Truck,ChevronRight}from'lucide-react';import'./style.css';
const menu=[
{cat:'Popular',items:[['Chicken Gyros Wrap',8.5,'Grilled chicken gyros served with lettuce, tzatziki, fries, pita bread, tomato & onions','wrap'],['Mix Grill for 2',30,'Chicken & pork gyros, chops, loukaniko, skewers, tzatziki, fries, pita breads','grill'],['Halloumi Pitta',8.5,'Grilled halloumi served with fries, pitta bread, tomato, onions & tzatziki','pitta']]},
{cat:'Sides',items:[['Fries',3.6,'Large portion of fries','fries'],['Pitta Bread',1.5,'Warm Greek-style pitta bread','pitta'],['Tzatziki',3.8,'Greek yoghurt dip with cucumber, garlic and olive oil','dip'],['Feta Cheese',4.5,'Greek feta sprinkled with olive oil','feta']]},
{cat:'Main Dishes',items:[['Pork Skewer',12.8,'Two grilled pork skewers served with fries, pitta bread, tomato, onions & tzatziki','skewer'],['Chicken Skewer',12.8,'Two grilled chicken skewers served with lettuce, tzatziki, fries, pitta bread, tomato & onions','skewer'],['Chicken or Pork Gyros',12.8,'Grilled gyros served with lettuce, tzatziki, fries, pitta bread, tomato & onions','gyros'],['Lamb Chops',14,'Five grilled lamb chops served with lettuce, tzatziki, fries, pitta bread, tomato & onions','chops']]},
{cat:'Platters',items:[['Mix Grill for 4',50,'Chicken & pork gyros, lamb chops, loukaniko, skewers, fries, 4 pitta breads, tomato & onions','platter']]},
{cat:'Drinks',items:[['Coca Cola 330ml',2.2,'Can drink','drink'],['Fanta Orange 330ml',2.1,'Can drink','drink'],['Highland Spring Water 500ml',1,'Still water','drink']]}
];
const extras=[['Extra Chicken',2.5],['Extra Tzatziki',.8],['Extra Fries',1.5],['No Onions',0]];
function price(n){return '£'+n.toFixed(2)}function Food({type}){return <div className={'food '+type}><span>{type==='drink'?'🥤':type==='fries'?'🍟':type==='dip'?'🥣':type==='feta'?'🧀':type==='platter'?'🍖':'🌯'}</span></div>}
function App(){const[screen,setScreen]=useState('home'),[cat,setCat]=useState('Popular'),[selected,setSelected]=useState(null),[cart,setCart]=useState([]);const cats=menu.map(x=>x.cat);const items=menu.find(x=>x.cat===cat)?.items||menu[0].items;const total=useMemo(()=>cart.reduce((s,i)=>s+i.total*i.qty,0),[cart]);function add(item,ex=[]){let extrasTotal=ex.reduce((s,e)=>s+e[1],0);setCart(c=>[...c,{name:item[0],base:item[1],desc:item[2],type:item[3],extras:ex,total:item[1]+extrasTotal,qty:1}]);setScreen('cart')}function Layout({children}){return <div className="phone"><div className="status">9:41 <span>●●●  Wi‑Fi  🔋</span></div>{children}</div>}
function Splash(){return <Layout><main className="splash"><img src="/assets/logo.png"/><h1>GYROMANIA</h1><p>AUTHENTIC GREEK FLAVOURS<br/>DELIVERED TO YOU</p><button onClick={()=>setScreen('menu')}>ORDER NOW</button><button className="outline" onClick={()=>setScreen('menu')}>COLLECTION</button></main></Layout>}
function Menu(){return <Layout><div className="top"><div><h2>GYROMANIA</h2><p><MapPin size={14}/> Delivery to <b>SW1A 1AA</b></p></div><div className="icons"><Bell/><Search/></div></div><div className="chips">{cats.map(c=><button onClick={()=>setCat(c)} className={cat===c?'active':''}>{c}</button>)}</div><h3>{cat.toUpperCase()}</h3><div className="list">{items.map((it,i)=><div className="card" onClick={()=>{setSelected(it);setScreen('product')}}><Food type={it[3]}/><div><b>{it[0]}</b><p>{it[2]}</p><strong>{price(it[1])}</strong></div><button className="round" onClick={(e)=>{e.stopPropagation();add(it)}}><Plus size={18}/></button></div>)}</div><Nav screen={screen} setScreen={setScreen} cart={cart}/></Layout>}
function Product(){const[ex,setEx]=useState([extras[1]]);if(!selected)return <Menu/>;let t=selected[1]+ex.reduce((s,e)=>s+e[1],0);return <Layout><button className="back" onClick={()=>setScreen('menu')}><ArrowLeft/></button><Food type={selected[3]}/><section className="product"><Heart className="heart"/><h2>{selected[0]} <span>{price(selected[1])}</span></h2><p>{selected[2]}</p><h4>ADD EXTRAS</h4>{extras.map(e=><label className="extra"><input type="checkbox" checked={ex.some(x=>x[0]===e[0])} onChange={ev=>setEx(ev.target.checked?[...ex,e]:ex.filter(x=>x[0]!==e[0]))}/><span>{e[0]}</span><b>{price(e[1])}</b></label>)}<h4>SPECIAL INSTRUCTIONS</h4><input className="note" placeholder="Add a note (e.g. no onions, extra spicy...)"/><div className="addbar"><div><button><Minus/></button><span>1</span><button><Plus/></button></div><button onClick={()=>add(selected,ex)}>ADD TO CART&nbsp; {price(t)}</button></div></section></Layout>}
function Cart(){return <Layout><h2 className="center">YOUR CART</h2><div className="list cart">{cart.map((it,idx)=><div className="card"><Food type={it.type}/><div><b>{it.name}</b><p>{it.extras.map(e=>e[0]).join(', ')}</p><strong>{price(it.total)}</strong></div><div className="qty"><button onClick={()=>setCart(c=>c.filter((_,i)=>i!==idx))}>−</button><span>{it.qty}</span><button onClick={()=>setCart(c=>c.map((x,i)=>i===idx?{...x,qty:x.qty+1}:x))}>+</button></div></div>)}</div><div className="summary"><p>Subtotal <b>{price(total)}</b></p><p>Delivery Fee <b>£2.50</b></p><h3>Total <b>{price(total?total+2.5:0)}</b></h3><button onClick={()=>setScreen('checkout')}>CHECKOUT</button><button className="outline" onClick={()=>setScreen('menu')}>CONTINUE SHOPPING</button></div><Nav screen={screen} setScreen={setScreen} cart={cart}/></Layout>}
function Checkout(){return <Layout><button className="back" onClick={()=>setScreen('cart')}><ArrowLeft/></button><h2 className="center">CHECKOUT</h2><div className="checkout"><h4>DELIVERY TO</h4><p>John Smith<br/>10 Downing Street, London<br/>SW1A 2AA</p><h4>DELIVERY TIME</h4><button className="pill">ASAP (30–45 mins)</button><button className="pill dark">Schedule for later</button><h4>PAYMENT METHOD</h4>{['Card  •••• 4242','Apple Pay','Google Pay'].map((p,i)=><div className={i===0?'pay sel':'pay'}>{p}<Circle size={16}/></div>)}<h3>Total <b>{price(total+2.5)}</b></h3><button onClick={()=>setScreen('tracking')}>PLACE ORDER</button><small>By placing an order you agree to our Terms & Conditions</small></div></Layout>}
function Tracking(){return <Layout><button className="back" onClick={()=>setScreen('menu')}><ArrowLeft/></button><section className="track"><h2>ORDER #1234</h2><h3>PREPARING YOUR ORDER</h3><p>We’ve received your order and our team is preparing your food.</p>{['Order Received','Preparing','On The Way','Delivered'].map((s,i)=><div className="step">{i<2?<CheckCircle2/>:<Circle/>}<span>{s}</span><b>{i===0?'9:41 AM':i===1?'9:45 AM':''}</b></div>)}<Truck size={110} className="ghost"/><div className="eta"><small>ESTIMATED DELIVERY</small><b>30 - 45 MIN</b></div><a>VIEW ORDER DETAILS</a></section><Nav screen={screen} setScreen={setScreen} cart={cart}/></Layout>}
function Admin(){return <Layout><h2 className="center">ADMIN DEMO</h2><section className="checkout"><h4>NEW ORDER</h4><p>Chicken Gyros Wrap + Extra Tzatziki<br/>Mix Grill for 2<br/>Halloumi Pitta</p><h3>Total <b>£50.30</b></h3><button>ACCEPT & PRINT RECEIPT</button><button className="outline">MARK READY</button></section></Layout>}
function Nav({screen,setScreen,cart}){return <nav>{[['home',Home],['menu',ReceiptText],['cart',ShoppingCart],['tracking',Clock],['admin',User]].map(([s,I])=><button className={screen===s?'on':''} onClick={()=>setScreen(s)}><I size={20}/>{s==='cart'&&cart.length?<em>{cart.length}</em>:null}<small>{s}</small></button>)}</nav>}
return screen==='home'?<Splash/>:screen==='menu'?<Menu/>:screen==='product'?<Product/>:screen==='cart'?<Cart/>:screen==='checkout'?<Checkout/>:screen==='admin'?<Admin/>:<Tracking/>}
createRoot(document.getElementById('root')).render(<App/>);
